
<div class="content">
    <div class="container">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <!--<h4 class="page-title">Admins</h4>-->
                <ol class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->url('portal') ?>">Dashboard</a>
                    </li>
                    <li class="active">
                        Articles
                    </li>
                </ol>
            </div>
        </div>

        <!--Custom Toolbar-->
        <!--===================================================-->
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title"><b>Articles</b></h4>
                    <p class="text-muted font-13">
                        News Articles
                    </p>
                    <?php if (isset($successMsgs) && count($successMsgs) > 0): ?>
                        <div class="alert alert-success alert-dismissible">
                            <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                            <?php
                            foreach ($successMsgs as $msg) {
                                echo $msg . ' <br/>';
                            }
                            ?>
                        </div>
                        <?php endif; ?>
                        <?php if (isset($errors) && count($errors) > 0): ?>
                        <div class="alert alert-danger alert-dismissible">
                            <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                            <?php
                            foreach ($errors as $msg) {
                                echo $msg . ' <br/>';
                            }
                            ?>
                        </div>
                    <?php endif; ?>
                    <div class="bootstrap-table">
                        <div class="fixed-table-toolbar">
                            <div class="bars pull-left">
                                <?php if (in_array(4,$this->layout()->permissions[4])):?>
                                <button id="demo-delete-row" class="btn btn-danger delete" disabled="" data-href="<?php echo $this->url('portal/articles',array('action'=>'delete'))?>">
                                    <i class="fa fa-trash-o m-r-5"></i>
                                    Delete
                                </button>
                                <?php endif;?>
                                <?php if (in_array(3,$this->layout()->permissions[4])):?>
                                <button id="demo-delete-row" class="btn btn-warning status" disabled="" data-val="2" data-href="<?php echo $this->url('portal/articles',array('action'=>'status'))?>">
                                    <i class="fa fa-times m-r-5"></i>
                                    Inactive
                                </button>
                                <button id="demo-delete-row" class="btn btn-success status" disabled="" data-val="1" data-href="<?php echo $this->url('portal/articles',array('action'=>'status'))?>">
                                    <i class="fa fa-check m-r-5"></i>
                                    Active
                                </button>
                                <?php endif;?>
                                <?php if (in_array(2,$this->layout()->permissions[4])):?>
                                <a id="demo-btn-addrow" class="btn btn-default" href="<?php echo $this->url('portal/articles', array('action' => 'add')); ?>">
                                    <i class="fa fa-plus m-r-5"></i>
                                    Add New Article
                                </a>
                                <?php endif;?>
                            </div>
                            <!--<div class="columns columns-right btn-group pull-right">
                                <button class="btn btn-default" title="Refresh" name="refresh" type="button">
                                    <i class="glyphicon glyphicon-refresh icon-refresh"></i>
                                </button>
                                <button class="btn btn-default" title="Toggle" name="toggle" type="button">
                                    <i class="glyphicon glyphicon-list-alt icon-list-alt"></i>
                                </button>

                            </div>-->
                            <div class="pull-right search">
                                <form name="search" action="" method="get">
                                    <input class="form-control" type="text" placeholder="Search" name="search">
                                </form>
                            </div>
                        </div>
                        <div class="fixed-table-container" style="padding-bottom: 0px;">
                            <div class="fixed-table-body">
                                <table class="table-bordered ">
                                    <thead>
                                        <tr>
                                            <th ><input type="checkbox" class="check-all" style="margin-left: 30px !important" /></th>
                                            <th >Category</th>
                                            <th >Title</th>
                                            <th >Summary</th>
                                            <th >Meta Data</th>
                                            <th >Created On</th>
                                            <th >Created By</th>
                                            <th >Status</th>
                                            <th >Actions</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <?php if (isset($articles) && count($articles) > 0): ?>
                                            <?php foreach ($articles as $article):?>
                                                <tr>
                                                    <td>#<?php echo isset($article->articleId) ? $article->articleId : ''; ?> <input type="checkbox" class="check-it" value="<?php echo isset($article->articleId) ? $article->articleId : ''; ?>" /></td>
                                                    <td><?php echo isset($article->category) ? $article->category : 'NA'; ?></td>
                                                    <td><?php echo (isset($article->title) && !empty($article->title)) ? $article->title : 'NA'; ?></td>
                                                    <td>
                                                        <button class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#panel-modal<?php echo isset($article->articleId) ? $article->articleId : ''; ?>">View</button>
                                                        <div id="panel-modal<?php echo isset($article->articleId) ? $article->articleId : ''; ?>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                                                            <div class="modal-dialog">
                                                                <div class="modal-content p-0 b-0">
                                                                    <div class="panel panel-color panel-primary">
                                                                        <div class="panel-heading"> 
                                                                            <button type="button" class="close m-t-5" data-dismiss="modal" aria-hidden="true">×</button> 
                                                                            <h3 class="panel-title">Content</h3> 
                                                                        </div> 
                                                                        <div class="panel-body"> 
                                                                            <img src="<?php echo (isset($article->filePath) && !empty($article->filePath)) ? $article->filePath : 'NA'; ?>" width="200" height="200" /><br />
                                                                            <?php echo (isset($article->summary) && !empty($article->summary)) ? $article->summary : 'NA'; ?>
                                                                        </div> 
                                                                    </div>
                                                                </div><!-- /.modal-content -->
                                                            </div><!-- /.modal-dialog -->
                                                        </div><!-- /.modal -->
                                                    </td>
                                                    <td>
                                                        <button class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#tabs-modal<?php echo isset($article->articleId) ? $article->articleId : ''; ?>">View</button>
                                                        <div id="tabs-modal<?php echo isset($article->articleId) ? $article->articleId : ''; ?>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                                                            <div class="modal-dialog">
                                                                <div class="modal-content p-0">
                                                                    <ul class="nav nav-tabs navtab-bg nav-justified">
                                                                        <li class="active">
                                                                            <a href="#metaTitle" data-toggle="tab" aria-expanded="true"> 
                                                                                <span class="visible-xs"><i class="fa fa-home"></i></span> 
                                                                                <span class="hidden-xs">Meta Title</span> 
                                                                            </a> 
                                                                        </li> 
                                                                        <li class=""> 
                                                                            <a href="#metaDescription" data-toggle="tab" aria-expanded="false"> 
                                                                                <span class="visible-xs"><i class="fa fa-user"></i></span> 
                                                                                <span class="hidden-xs">Meta Description</span> 
                                                                            </a> 
                                                                        </li> 
                                                                        <li class=""> 
                                                                            <a href="#metaKeywords" data-toggle="tab" aria-expanded="false"> 
                                                                                <span class="visible-xs"><i class="fa fa-envelope-o"></i></span> 
                                                                                <span class="hidden-xs">Meta Keywords</span> 
                                                                            </a> 
                                                                        </li>
                                                                    </ul> 
                                                                    <div class="tab-content"> 
                                                                        <div class="tab-pane active" id="metaTitle"> 
                                                                            <?php echo (isset($article->metaTitle) && !empty($article->metaTitle)) ? $article->metaTitle : 'NA'; ?>
                                                                        </div> 
                                                                        <div class="tab-pane" id="metaDescription">
                                                                            <?php echo (isset($article->metaDescription) && !empty($article->metaDescription)) ? $article->metaDescription : 'NA'; ?>
                                                                        </div> 
                                                                        <div class="tab-pane" id="metaKeywords">
                                                                            <?php echo (isset($article->metaKeywords) && !empty($article->metaKeywords)) ? $article->metaKeywords : 'NA'; ?>
                                                                        </div> 
                                                                    </div> 
                                                                </div><!-- /.modal-content -->
                                                            </div><!-- /.modal-dialog -->
                                                        </div><!-- /.modal -->
                                                    </td>
                                                    <td><?php echo isset($article->createdDate) ? date('D d, M Y', strtotime($article->createdDate)) : ''; ?></td>
                                                    <td><?php echo isset($article->creator) ? $article->creator : ''; ?></td>
                                                    <td><?php echo isset($article->label) ? $article->label : ''; ?></td>
                                                    <td class="actions">
                                                        <?php if (in_array(3,$this->layout()->permissions[4])):?>
                                                        <button class="on-default edit-row" onclick="document.location.href = '<?php echo $this->url('portal/articles',array('action'=>'edit','id'=>$article->articleId))?>'">
                                                            <i class="fa fa-pencil"></i>
                                                        </button>
                                                        <?php endif;?>
                                                        <?php if (in_array(4,$this->layout()->permissions[4])):?>
                                                        <button class="delete" data-href="<?php echo $this->url('portal/articles',array('action'=>'delete','id'=>$article->articleId))?>">
                                                            <i class="fa fa-trash-o"></i>
                                                        </button>
                                                        <?php endif;?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td colspan="9">No records found..!!</td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>

                            <?php
                            echo $this->paginationControl(
                                    $articles, // the paginator object
                                    'sliding', // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                                    array('partial/portalPagination.phtml', 'Portal'), // the partial to use to render the control
                                    array('route' => 'portal/articles')  //'routeParams' => $this->postedData  the route to link to when a user clicks a control link
                            );
                            ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>


    </div> <!-- container -->

</div> <!-- content -->

