<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>

                <!--<li class="text-muted menu-title">Navigation</li>-->

                <li class="has_sub">
                    <a href="<?php echo $this->url('portal');?>" class="waves-effect <?php echo (isset($this->controller) && $this->controller == '\Index')?'active':'';?>"><i class="ti-home"></i> <span> Dashboard </span> </a>
                </li>

                <li class="has_sub">
                    <a href="#" class="waves-effect <?php echo (isset($this->controller) && in_array($this->controller,array('\Admins')))?'active':'';?>"><i class="fa fa-group"></i><!--<span class="label label-primary pull-right">6</span>--><span> Users </span> </a>
                    <ul class="list-unstyled">
                        <li class="<?php echo (isset($this->controller) && $this->controller == '\Admins')?'active':'';?>"><a href="<?php echo $this->url('portal/admins')?>" >Admins</a></li>
                    </ul>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->