<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link rel="shortcut icon" href="<?php echo $this->basePath('images/portal/favicon_1.ico'); ?>">

        <?php echo $this->headTitle('Techquer Portal' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'images/portal/favicon_1.ico', 'href' => $this->basePath() . '/images/portal/favicon.ico'))
                ->appendStylesheet($this->basePath('css/portal/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('css/portal/core.css'))
                ->appendStylesheet($this->basePath('css/portal/components.css'))
                ->appendStylesheet($this->basePath('css/portal/icons.css'))
                ->appendStylesheet($this->basePath('css/portal/pages.css'))
                ->appendStylesheet($this->basePath('css/portal/responsive.css'))
                ->appendStylesheet($this->basePath('plugins/bootstrap-table/dist/bootstrap-table.min.css'))
                ->appendStylesheet($this->basePath('plugins/select2/select2.css'))
                ->appendStylesheet($this->basePath('plugins/sweetalert/dist/sweetalert.css'));
        ?>

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <?php
        echo $this->headScript()
                ->appendFile($this->basePath('js/portal/jquery.min.js'))
                ->appendFile($this->basePath('js/portal/modernizr.min.js'));
        ?>
        <script>
            var resizefunc = [];
            var basePath = '<?php echo $this->basePath('portal/'); ?>';
        </script>
    </head>


    <body class="fixed-left">

        <div class="animationload">
            <div class="loader"></div>
        </div>

        <!-- Begin page -->
        <div id="wrapper">

            <?php echo $this->partial('portal/header'); ?>
            <?php echo $this->partial('sidebar'); ?>
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <?php echo $this->content; ?>

                <footer class="footer">
                    <?php echo date('Y') ?> © TechQuer.
                </footer>

            </div>
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->
            <!-- Right Sidebar -->
            <div class="side-bar right-bar nicescroll">
                <h4 class="text-center">Chat</h4>
                <div class="contact-list nicescroll">
                    <ul class="list-group contacts-list">
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-1.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Chadengle</span>
                                <i class="fa fa-circle online"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-2.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Tomaslau</span>
                                <i class="fa fa-circle online"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-3.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Stillnotdavid</span>
                                <i class="fa fa-circle online"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-4.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Kurafire</span>
                                <i class="fa fa-circle online"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-5.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Shahedk</span>
                                <i class="fa fa-circle away"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-6.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Adhamdannaway</span>
                                <i class="fa fa-circle away"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-7.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Ok</span>
                                <i class="fa fa-circle away"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-8.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Arashasghari</span>
                                <i class="fa fa-circle offline"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-9.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Joshaustin</span>
                                <i class="fa fa-circle offline"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <div class="avatar">
                                    <img src="<?php echo $this->basePath('images/portal/users/avatar-10.jpg'); ?>" alt="">
                                </div>
                                <span class="name">Sortino</span>
                                <i class="fa fa-circle offline"></i>
                            </a>
                            <span class="clearfix"></span>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /Right-bar -->

        </div>
        <!-- END wrapper -->
        <!-- jQuery  -->
        <script src="<?php echo $this->basePath('js/portal/jquery.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/detect.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/fastclick.js'); ?>"></script>

        <script src="<?php echo $this->basePath('js/portal/jquery.slimscroll.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.blockUI.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/waves.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/wow.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.nicescroll.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.scrollTo.min.js'); ?>"></script>

        <script src="<?php echo $this->basePath('plugins/peity/jquery.peity.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/waypoints/lib/jquery.waypoints.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/counterup/jquery.counterup.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/raphael/raphael-min.js'); ?>"></script>

        <script src="<?php echo $this->basePath('plugins/jquery-knob/jquery.knob.js'); ?>"></script>

        <script src="<?php echo $this->basePath('js/portal/jquery.core.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.app.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/sweetalert/dist/sweetalert.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.sweet-alert.init.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/common.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/tinymce/tinymce.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/select2/select2.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('plugins/bootstrap-filestyle/src/bootstrap-filestyle.min.js'); ?>"></script>

        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                $('.counter').counterUp({
                    delay: 100,
                    time: 1200
                });

                $(".knob").knob();

            });
        </script>




    </body>
</html>