<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link rel="shortcut icon" href="<?php echo $this->basePath('images/portal/favicon_1.ico'); ?>">

        <?php echo $this->headTitle('Techquer Portal Login' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'images/portal/favicon_1.ico', 'href' => $this->basePath() . '/images/portal/favicon.ico'))
                ->appendStylesheet($this->basePath('plugins/morris/morris.css'))
                ->appendStylesheet($this->basePath('css/portal/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('css/portal/core.css'))
                ->appendStylesheet($this->basePath('css/portal/components.css'))
                ->appendStylesheet($this->basePath('css/portal/icons.css'))
                ->appendStylesheet($this->basePath('css/portal/pages.css'))
                ->appendStylesheet($this->basePath('css/portal/responsive.css'));
        ?>

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <?php
        echo $this->headScript()
                ->appendFile($this->basePath('js/portal/jquery.min.js'))
                ->appendFile($this->basePath('js/portal/modernizr.min.js'));
        ?>

    </head>
    <body>

        <div class="animationload">
            <div class="loader"></div>
        </div>

        <div class="account-pages"></div>
        <div class="clearfix"></div>

        <?php echo $this->content; ?>

        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="<?php echo $this->basePath('js/portal/jquery.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/detect.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/fastclick.js'); ?>"></script>

        <script src="<?php echo $this->basePath('js/portal/jquery.slimscroll.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.blockUI.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/waves.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/wow.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.nicescroll.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.scrollTo.min.js'); ?>"></script>

        <script src="<?php echo $this->basePath('js/portal/jquery.core.js'); ?>"></script>
        <script src="<?php echo $this->basePath('js/portal/jquery.app.js'); ?>"></script>

    </body>
</html>