<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Techquer' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
                ->appendStylesheet($this->basePath('css/style.css'))
                ->appendStylesheet($this->basePath('css/responsive.css'))
                ->appendStylesheet($this->basePath('css/theme.css'));
        ?>

        <!-- Scripts -->
<?php
echo $this->headScript()
        ->appendFile($this->basePath('js/jquery-1.11.2.js'))
        ->appendFile($this->basePath('js/modernizr-2.8.3-respond-1.4.2.min.js'));
?>

    </head>
    <body class="home page page-id-4 page-template page-template-template_home-php">
        <!-- TOP NAV -->
        <div class="navbar navbar-default top-nav-bar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".topmenu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse topmenu">
                    <div class="menu-header-templates-menu-container">
                        <ul class="nav navbar-nav">
                            <li><a href="about.html">About</a></li>
                            <li><a href="article.html">Article</a></li>
                            <li><a href="article-review.html">Article Review</a></li>
                            <li><a href="archives.html">Archives</a></li>
                            <li><a href="category.html">Category</a></li>
                            <li><a href="fullwidth.html">Full Width</a></li>
                            <li><a href="shortcodes.html">Shortcodes</a></li>
                            <li><a href="404.html">404</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>        
                </div>
            </div>
        </div>
        <!-- LOGO AREA -->
        <div class="fullwidth bg-pink">
            <div class="container">
                <div class="col-md-6 col-xs-12">
                    <div class="logo">
                        <h1><a href="index.html" title=" weekend Magazine">Weekend Magazine</a></h1>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <div id="ads120_60-widget-2" class="ads120-60 ads-one">
                        <div class="ad-cell">
                            <a href="#" target="_blank" >                 
                                <img src="http://jkthemes.com/weekend/Html/img/ad-468x60-2.png " alt="">
                            </a>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- MAIN NAV -->
        <div class="fullwidth navbar navbar-default main-nav-bar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".mainmenu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse mainmenu">
                    <div class="menu-primary-navigation-container">
                        <ul id="menu-primary-navigation" class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Home <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="index.html">Home</a></li>
                                    <li><a href="index2.html">Home 2</a></li>
                                    <li><a href="index3.html">Home Dark 1</a></li>
                                    <li><a href="index4.html">Home Dark 2</a></li>
                                    <li><a href="index5.html">Home Light 1</a></li>
                                    <li><a href="index6.html">Home Light 2</a></li>
                                </ul>
                            </li>
                            <li><a href="#">News</a></li>
                            <li><a href="#">Economy</a></li>
                            <li><a href="#">Sports</a></li>
                            <li><a href="#">Shows</a></li>
                            <li><a href="#">Culture &#038; Art</a></li>
                            <li><a href="#">Gossips</a></li>
                            <li><a href="#">Fashion</a></li>
                            <li><a href="#">Health &#038; Body</a></li>
                            <li><a href="#">Technology</a></li>
                            <li><a href="#">Science</a></li>
                        </ul>
                    </div>        
                </div>
            </div>
        </div>
        <?php echo $this->content; ?>
        <div class="footer">
            <div class="footer-top">
                <div class="container">
                    <div class="pull-left">
                        <div id="text-6">     
                            <div class="textwidget"><a href="#">Weekend Magazine</a> &copy; 2015 All rights reserved</div>
                        </div>          
                    </div>
                    <div class="pull-right hidden-xs">
                        <div id="text-7">     
                            <div class="textwidget">Theme by <a title="Email me now" href="#">JKthemes</a></div>
                        </div>          
                    </div>
                </div>
            </div>
            <div class="footer-bottom hidden-xs">
                <div class="container">
                    <div id="nav_menu-2">
                        <div class="menu-footer-menu-container">
                            <ul id="menu-footer-menu" class="menu">
                                <li><a href="#">Home</a></li>
                                <li><a href="#">News</a></li>
                                <li><a href="#">Economy</a></li>
                                <li><a href="#">Sports</a></li>
                                <li><a href="#">Shows</a></li>
                                <li><a href="#">Culture &#038; Art</a></li>
                                <li><a href="#">Gossips</a></li>
                                <li><a href="#">Fashion</a></li>
                                <li><a href="#">Health &#038; Body</a></li>
                                <li><a href="#">Technology</a></li>
                                <li><a href="#">Science</a></li>
                            </ul>
                        </div>
                    </div>          
                    <a class="footer-nav-scroll pull-right"></a>
                </div>
            </div>
        </div>
        <script src="<?php echo $this->basePath('js/bootstrap.min.js');?>"></script>
        <script src="<?php echo $this->basePath('js/jquery.bxslider.min.js');?>"></script>
        <script src="<?php echo $this->basePath('js/custom.js');?>"></script>
    </body>
</html>
