<div class="container">
    <div class="main col-md-6 col-xs-12 col-md-push-3">

        <div id="news_ticker" class="widget news_ticker">
            <div class="col-md-2 col-xs-12">
                <h4 class="ticker-heading">Breaking</h4>
            </div>
            <div class="col-md-10 col-xs-12">
                <ul class="ticker">
                    <li>
                        <span class="ticker-time">7:34 pm</span>
                        <a class="ticker-news" href="#">The tenet of the film and book is that the universe</a>
                    </li>
                    <li>
                        <span class="ticker-time">1:29 am</span>
                        <a class="ticker-news" href="#">The tenet of the film and book is that the universe</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="slider widget fullwidth">
            <ul class="slider-content">
                <li>
                    <div class="image">
                        <img src="http://jkthemes.com/weekend/Html/img/slider.jpg" alt="">
                    </div>
                    <div class="info">
                        <span class="slider-time">7:34 pm</span>
                        <span class="slider-featured">Featured</span>
                        <div class="clear"></div>
                        <h2>
                            <a href="#" class="slider-title">Obama makes his final mandate on White House</a>
                        </h2>
                    </div>
                </li>
            </ul>
        </div>

        <div class="box-content widget fullwidth">
            <h4 class="widget-title">News</h4>
            <div class="widget-content">
                <ul class="news-carousel">
                    <li>
                        <a href="#">
                            <span class="comment-count">13</span>
                            <img src="http://jkthemes.com/weekend/Html/img/news1.jpg" width="270" alt="">
                        </a>
                        <h4 class="news-title"><a href="#">Alboroza ft Kymanus Marli Natural Mystic</a></h4>
                        <p>Nunc faucibus, nisi non sagittis hendrerit, leo turpis interdum sem, non tincidunt pur us justo id ipsum some other word.</p>
                    </li>
                    <li>
                        <a href="#">
                            <span class="comment-count">4</span>
                            <img src="http://jkthemes.com/weekend/Html/img/news2.jpg" width="270" alt="">
                        </a>
                        <h4 class="news-title"><a href="#">Though it was an exceptionally cold winter</a></h4>
                        <p>There is no correct set of tools every developer should be using. The right tool is the one best suited to you we've list.</p>
                    </li>
                    <li>
                        <a href="#">
                            <span class="comment-count">13</span>
                            <img src="http://jkthemes.com/weekend/Html/img/news1.jpg" width="270" alt="">
                        </a>
                        <h4 class="news-title"><a href="#">Alboroza ft Kymanus Marli Natural Mystic</a></h4>
                        <p>Nunc faucibus, nisi non sagittis hendrerit, leo turpis interdum sem, non tincidunt pur us justo id ipsum some other word.</p>
                    </li>
                    <li>
                        <a href="#">
                            <span class="comment-count">4</span>
                            <img src="http://jkthemes.com/weekend/Html/img/news2.jpg" width="270" alt="">
                        </a>
                        <h4 class="news-title"><a href="#">Though it was an exceptionally cold winter</a></h4>
                        <p>There is no correct set of tools every developer should be using. The right tool is the one best suited to you we've list.</p>
                    </li>
                </ul>
            </div>
        </div>

        <div class="review-posts widget fullwidth">
            <h4 class="widget-title">Reviews</h4>
            <div class="widget-content">
                <ul class="reviews">
                    <li>
                        <div class="review_header clearfix">
                            <div class="thumb">
                                <a href="#">
                                    <span class="comment-count">13</span>
                                    <img src="http://jkthemes.com/weekend/Html/img/review1.jpg" alt="">
                                </a>
                            </div>
                            <div class="ratings">
                                <div class="review-box review-top review-percentage">
                                    <ul>
                                        <li>
                                            <span class="rating-before">Special Effects<span class="rating-score">4.3</span></span>
                                        </li>
                                        <li>
                                            <span class="rating-before">Story Line<span class="rating-score">4.7</span></span>
                                        </li>
                                        <li>
                                            <span class="rating-before">Casting<span class="rating-score">4.1</span></span>
                                        </li>
                                    </ul>
                                    <div class="review-summary">
                                        <ul>
                                            <li>
                                                <span class="rating-before last">Overall<span class="rating-score">4.9</span></span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h4 class="rating-title"><a href="#">Startup business, another masterpiece from Kingdom</a></h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a pag  when looking at its layout. The point of using Lorem Ipsum is that it has.</p>
                    </li>
                    <li>
                        <div class="review_header clearfix">
                            <div class="thumb">
                                <a href="#">
                                    <span class="comment-count">13</span>
                                    <img src="http://jkthemes.com/weekend/Html/img/review2.jpg" alt="">
                                </a>
                            </div>
                            <div class="ratings">
                                <div class="review-box review-top review-percentage">
                                    <ul>
                                        <li>
                                            <span class="rating-before">Special Effects<span class="rating-score">4.3</span></span>
                                        </li>
                                        <li>
                                            <span class="rating-before">Story Line<span class="rating-score">4.7</span></span>
                                        </li>
                                        <li>
                                            <span class="rating-before">Casting<span class="rating-score">4.1</span></span>
                                        </li>
                                    </ul>
                                    <div class="review-summary">
                                        <ul>
                                            <li>
                                                <span class="rating-before last">Overall<span class="rating-score">4.9</span></span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h4 class="rating-title"><a href="#">The useless parade of bels</a></h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a pag  when looking at its layout. The point of using Lorem Ipsum is that it has.</p>
                    </li>
                </ul>
            </div>
        </div>

        <div class="widget fullwidth post-single">
            <h4 class="widget-title">Gossips</h4>
            <div class="widget-content">
                <ul>
                    <li>
                        <a href="#"><img src="http://jkthemes.com/weekend/Html/img/gossip1.jpg" alt=""></a>
                        <h4 class="list-title"><a href="#">The book is very much influenced by Wallace</a></h4>
                        <p>Metus massa, blandit dio proin quis tortor orci tiam aris justo dignissim congue donec congue lacinia dui, a porttitor lectus lorem ipsun. Praesent id metus massa, ut blandit odio proin quis tortor orc.</p>
                    </li>
                    <li>
                        <a href="#"><img src="http://jkthemes.com/weekend/Html/img/gossip2.jpg" alt=""></a>
                        <h4 class="list-title"><a href="#">NYC's Most Romantic Valentine's Day Places</a></h4>
                        <p>From a free cruise to a bar with an aphrodisiac-inspired menu, the author of Naughty New York reveals the city's best things to do for Valentine's Day some other line to fill this row.</p>
                    </li>
                    <li>
                        <a href="#"><img src="http://jkthemes.com/weekend/Html/img/gossip3.jpg" alt=""></a>
                        <h4 class="list-title"><a href="#">Who doesn't enjoy a free quickie? The iconic Staten Island </a></h4>
                        <p>Try a bit of al fresco inspiration at the gardens of the Cloisters Museum. Located on four acres overlooking the Hudson River in Manhattan's Fort Tryon Park, these enclosed quadrangles rate.</p>
                    </li>
                    <li>
                        <a href="#"><img src="http://jkthemes.com/weekend/Html/img/gossip4.jpg" alt=""></a>
                        <h4 class="list-title"><a href="#">In the mood for a more festive cruise</a></h4>
                        <p>Ready to discover a new angle on art appreciation? Some of the most famous masterpieces ever created pay homage to the human body, and you'll find the best of them at the Met.</p>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="left-sidebar col-md-3 col-md-pull-6" role="complementary">

        <div id="text-html-widget-2" class="widget fullwidth text-html">

            <div>
                <div class="socialize">
                    <h4>SOCIALIZE</h4>
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clear"></div>
        </div>

        <div class="recent-widget widget padding-0" id="tabbed-widget">
            <ul class="nav nav-justified nav-tabs">
                <li class="active"><a href="#popular" data-toggle="tab">popular</a></li>
                <li><a href="#recent" data-toggle="tab">recent</a></li>
            </ul>
            <div class="tab-content padding-10">
                <div class="tab-pane fade in active" id="popular">
                    <ul class="post-list">
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">6</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab1.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">A wonderful serenity has taken possession</a></h4>
                        </li>
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">19</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab2.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">The Secret is based on the earlier film of the same name</a></h4>
                        </li>
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">2</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab3.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">The tenet of the film and book is that the universe</a></h4>
                        </li>
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">34</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab4.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">The book is very much influenced by Wallace</a></h4>
                        </li>
                    </ul>
                </div>
                <div class="tab-pane fade" id="recent">
                    <ul class="post-list">
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">6</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab1.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">A wonderful serenity has taken possession</a></h4>
                        </li>
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">19</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab2.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">The Secret is based on the earlier film of the same name</a></h4>
                        </li>
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">2</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab3.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">The tenet of the film and book is that the universe</a></h4>
                        </li>
                        <li>
                            <div class="thumb">
                                <a href="#">
                                    <span class="recent-count">34</span>
                                    <img width="60" height="60" src="http://jkthemes.com/weekend/Html/img/tab4.jpg" alt="">
                                </a>
                            </div>
                            <h4><a href="#">The book is very much influenced by Wallace</a></h4>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="video-widget-2" class="widget fullwidth video-widget">
            <h1 class="widget-title">Video of the day </h1>
            <iframe src="http://player.vimeo.com/video/18886355?wmode=opaque" width="210" height="125"></iframe>
        </div>

        <div id="flickr_photos-widget-2" class="widget fullwidth flickr-widget">
            <h1 class="widget-title">Flickr feed</h1>
            <script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=9&amp;display=latest&amp;size=s&amp;layout=x&amp;source=user&amp;user=10133335@N08"></script>
            <div class="clear"></div>
        </div>

        <div class="widget widget-counter col4">
            <h4 class="widget-title">Network</h4>
            <div class="widget-content">
                <div class="network">
                    <a href="https://www.facebook.com/NargisFakhri" target="_blank">
                        <span class="network-icon"><i class="fa fa-facebook"></i></span>
                        <p><span class="network-count facebook">12,575</span>Fans</p>
                    </a>
                    <a href="http://www.twitter.com/" target="_blank">
                        <span class="network-icon"><i class="fa fa-twitter"></i></span>
                        <p><span class="network-count twitter">9844</span>Followers</p>
                    </a>
                    <a href="http://vimeo.com/channels/27476" target="_blank">
                        <span class="network-icon rss"><i class="fa fa-rss"></i></span>
                        <p><span class="network-count rss">3714</span>Subscribers</p>
                    </a>
                </div>
            </div>
        </div>

        <div id="latest-tweets-widget-2" class="widget fullwidth twitter-widget">
            <h1 class="widget-title"> LATEST TWEETS</h1>
            <ul class="twitter-feeds">
                <li class="twitter-item">
                    <a href="http://twitter.com/heyitscourtxo" class="twitter-user">@heyitscourtxo</a>
                    why you're afraid? Ignore us #respect4all 
                    <span class="twitter-timestamp"><abbr title="2014/06/13 23:38:07">2014/06/13</abbr></span>
                </li>
                <li class="twitter-item">
                    <a href="http://twitter.com/heyitscourtxo" class="twitter-user">@heyitscourtxo</a>
                    why you're afraid? Ignore us #respect4all 
                    <span class="twitter-timestamp"><abbr title="2014/06/13 23:38:07">2014/06/13</abbr></span>
                </li>
                <li class="twitter-item">
                    <a href="http://twitter.com/heyitscourtxo" class="twitter-user">@heyitscourtxo</a>
                    why you're afraid? Ignore us #respect4all 
                    <span class="twitter-timestamp"><abbr title="2014/06/13 23:38:07">2014/06/13</abbr></span>
                </li>
            </ul>
            <a href="#" class="twitter_follow_button">Follow us on twitter</a>
        </div>

        <div id="facebook-widget-2" class="widget fullwidth facebook-widget">
            <h1 class="widget-title">Find us on Facebook </h1>
            <div class="facebook-box">
                <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FNargisFakhri&amp;width&amp;height=258&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;appId=706420439383255"   style="border:none;  height:258px;" ></iframe>
            </div>
        </div>

    </div>
    <div class="right-sidebar col-md-3" role="complementary">

        <div id="search-3" class="widget fullwidth widget_search">
            <form class="search" role="search" method="get" action="#">
                <input type="search" placeholder="Search &hellip;" value="" name="s" title="Search for:">
            </form>
        </div>

        <div id="categort-posts-widget-2" class="widget fullwidth categort-posts"><h1 class="widget-title">TV SHOWS </h1>
            <ul class="tvshows">
                <li>
                    <a href="#">
                        <span class="comment-count">11</span>
                        <img src="http://jkthemes.com/weekend/Html/img/tv1.jpg" alt="">
                    </a>
                    <h4><a href="#">See no changes all saw is faces mis placed hate makes disgrace</a></h4>
                </li>
                <li>
                    <a href="#">
                        <span class="comment-count">76</span>
                        <img src="http://jkthemes.com/weekend/Html/img/tv2.jpg" alt="">
                    </a>
                    <h4><a href="#">How to find water in the desert?</a></h4>
                </li>
            </ul>
            <div class="clear"></div>
        </div>

        <div class="widget featured-side">
            <div class="widget-content">
                <a href="#"><img src="http://jkthemes.com/weekend/Html/img/interview.jpg" alt=" "></a>
                <div class="featured-side-content">
                    <span class="featured-side-title">Interview</span>
                    <p class="featured-side-desc">Black eyed beans rolling on the list of Billsoard 100</p>
                </div>
            </div>
            <div class="clear"></div>
        </div>

        <div id="tag_cloud-2" class="widget fullwidth widget_tag_cloud">
            <h1 class="widget-title">Tags</h1>
            <div class="tagcloud">
                <a href="#">Portfolio</a>
                <a href="#">Typography</a>
                <a href="#">Type</a>
                <a href="#">Compaign</a>
                <a href="#">Illustration</a>
                <a href="#">Face</a>
                <a href="#">UI</a>
                <a href="#">Experience</a>
                <a href="#">Brand</a>
                <a href="#">Portfolio</a>
                <a href="#">Typography</a>
                <a href="#">Type</a>
                <a href="#">Compaign</a>
                <a href="#">Illustration</a>
                <a href="#">Face</a>
                <a href="#">UI</a>
                <a href="#">Experience</a>
                <a href="#">Brand</a>
            </div>
        </div>

        <div id="widget-survey" class="widget fullwidth widget-survey">
            <h1 class="widget-title">Survey</h1>
            <div class="widget-content">
                <p>What was the last time you slept on bed in your house?</p>
                <form action="#" method="post" class="mrgn-bottom-0">
                    <div class="form-group mrgn-bottom-0">
                        <div class="checkbox">
                            <label>
                                <input name="remember" value="1" type="checkbox"> Today
                            </label>
                        </div>
                    </div>
                    <div class="form-group mrgn-bottom-0">
                        <div class="checkbox">
                            <label>
                                <input name="remember" value="1" type="checkbox"> Yesterday
                            </label>
                        </div>
                    </div>
                    <div class="form-group mrgn-bottom-0">
                        <div class="checkbox">
                            <label>
                                <input name="remember" value="1" type="checkbox"> The day after tomorrow
                            </label>
                        </div>
                    </div>
                    <div class="form-group mrgn-bottom-0">
                        <div class="checkbox">
                            <label>
                                <input name="remember" value="1" type="checkbox"> Tomorrow
                            </label>
                        </div>
                    </div>
                    <div class="row survey">
                        <div class="col-md-6">
                            <button class="button vote">Vote</button>
                        </div>
                        <div class="col-md-6">
                            <button class="button">Results</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div id="widget-feedburner-2" class="widget fullwidth widget-feedburner">
            <h1 class="widget-title">Subscribe</h1>
            <div class="widget-feedburner-counter subscribe">
                <p>Subscribe to our RSS feed, be in touch with our articles, news, videos, freebies.</p>
                <form action="#" method="post">
                    <input class="feedburner-email input-subscribe" type="text" name="email"
                           value="Enter your e-mail address"
                           onfocus="if (this.value == 'Enter your e-mail address') {
                                       this.value = '';
                                   }"
                           onblur="if (this.value == '') {
                                       this.value = 'Enter your e-mail address';
                                   }">
                    <input class="feedburner-subscribe input-button" type="submit" name="submit" value="Add">
                </form>
            </div>
        </div>

        <div id="ads250_250-widget-2" class="widget fullwidth ads250_250-widget"><h1 class="widget-title">
                Advertisement</h1>
            <div class="ads250-250">
                <div class="ad-cell">
                    <a href="#"><img src="http://jkthemes.com/weekend/Html/img/ad-210x190.png" class="fullwidth" alt=""></a>
                </div>
            </div>
        </div>

    </div>

</div>
<?php //echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?>